### PR TITLE
pii bool -> piiLevel

### PR DESCRIPTION
**Pull request by chinatsu**
haven't tested extensively, but the following works as expected in /api:
```graphql
mutation {
  createDataproduct(input: {
    name: "abc", 
    group: "team@nav.no", 
    datasets:[
      {
        name: "my anonymised dataset", 
        pii: anonymised, 
        bigquery: {
          dataset: "dataset2"
          projectID: "team-dev-1337"
          table: "table1"
        }
      }
    ]
  }) {
    id
  }
}
```
and then verify that the dataset stores the anonymised pii level:

```graphql
query {
  dataproducts(limit: 100) {
    id,
    datasets {
      name,
      pii
    }
  }
  ```
  
  additionally, i have verified that existing datasets with `pii: true` has become `pii: "sensitive"`, and `pii: false` has become `pii: "none"`

### CODE REVIEW

**Comment by chinatsu** [comment]
ps: shouldn't be merged because it breaks the frontend atm :sweat_smile: 
will update the frontend to work with this soontm (after lunch?)

**Review by erikvatt — COMMENTED** [review]
It seems as though something went wrong with the graphql codegen, most of the field resolvers for dataset have been removed. See pkg/graph/datasets.resolvers.go

**Comment by erikvatt** [comment]
The unit and e2e tests need to be updated as well

**Comment by chinatsu** [comment]
oops, i think i deleted a bunch of stuff.. i'll try to fix it

**Comment by chinatsu** [comment]
should make things work as before: https://github.com/navikt/nada-frontend/pull/93

**Review by erikvatt — APPROVED** [review]

**Pull request merged**
